import { Award, PenTool, Users, Eye, Fingerprint, Clock, FileCheck } from 'lucide-react';

const benefits = [
    {
        icon: PenTool,
        title: "Expert Designers",
        description: "Your signature is handcrafted by real calligraphers, not generated by software."
    },
    {
        icon: Award,
        title: "Career-Focused Designs",
        description: "We create signatures designed for professional documents, contracts, and presentations."
    },
    {
        icon: Eye,
        title: "Elegant & Readable",
        description: "Our designs strike the perfect balance between unique artistic style and professional legibility."
    },
     {
        icon: Clock,
        title: "Delivered in 24 Hours",
        description: "Fast, clean, premium execution. No delays."
    },
    {
        icon: FileCheck,
        title: "Digital + Print Ready Files",
        description: "Use it everywhere: documents, PDFs, emails, business cards, branding, and more."
    },
    {
        icon: Fingerprint,
        title: "Personal Attention",
        description: "Your signature is tailored to the unique flow and character of your name, ensuring a truly personal mark."
    }
]


export default function BenefitsSection() {
    return (
        <section className="py-10">
            <div className="container mx-auto px-4">
                 <div className="text-center mb-6">
                    <h2 className="text-3xl font-headline font-bold">Why Thousands Choose SignaGenius</h2>
                    <p className="text-muted-foreground mt-2">Everything you need to elevate your image instantly.</p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 text-center">
                    {benefits.map(benefit => (
                        <div key={benefit.title} className="flex flex-col items-center">
                             <div className="bg-primary/10 text-primary p-3 rounded-full mb-2">
                                <benefit.icon className="w-8 h-8" />
                            </div>
                            <h3 className="text-xl font-headline font-semibold mb-1">{benefit.title}</h3>
                            <p className="text-muted-foreground">{benefit.description}</p>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    )
}
