import { Award, Clock, Download, RefreshCw, PenTool, CheckCircle, Star } from 'lucide-react';
import { Button } from '@/components/ui/button';

const benefits = [
    {
        icon: Star,
        title: "A Signature That Defines You",
        description: "Make a powerful impression with a unique signature designed to reflect your personality and profession."
    },
    {
        icon: PenTool,
        title: "Professional Calligraphers",
        description: "Your signature is handcrafted — not generated by software or AI."
    },
    {
        icon: Clock,
        title: "Delivered in 24 Hours",
        description: "Fast, clean, premium execution. No delays."
    },
    {
        icon: RefreshCw,
        title: "Unlimited Revisions",
        description: "We refine your signature until you say it's perfect. No extra fees. No limits."
    },
    {
        icon: Download,
        title: "Digital + Print Ready Files",
        description: "Use it everywhere — documents, PDFs, emails, business cards, branding, and more."
    },
]


export default function BenefitsSection() {
    return (
        <section className="py-20 bg-muted/50">
            <div className="container mx-auto px-4">
                <div className="text-center mb-12">
                    <h2 className="text-3xl font-headline font-bold">Why Thousands Choose SignaGenius™</h2>
                    <p className="text-muted-foreground mt-2">Everything you need to elevate your image instantly.</p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-x-8 gap-y-4">
                    {benefits.map((benefit, index) => (
                        <div key={index} className="flex items-start text-left gap-4">
                            <div className="text-primary mt-1">
                                <benefit.icon className="w-6 h-6" />
                            </div>
                            <div>
                                <h3 className="text-xl font-bold mb-2">{benefit.title}</h3>
                                <p className="text-muted-foreground">{benefit.description}</p>
                            </div>
                        </div>
                    ))}
                </div>
                 <div className="mt-12 text-center">
                    <Button
                        size="lg"
                        className="h-14 text-base md:text-lg min-w-[280px] bg-accent hover:bg-accent/90 text-accent-foreground font-semibold rounded-lg shadow-lg hover:shadow-xl transition-all animate-jiggle"
                        style={{ boxShadow: '0 4px 12px rgba(0,0,0,0.15)' }}
                    >
                        Create My Signature (50% Off)
                    </Button>
                </div>
            </div>
        </section>
    )
}
